// Copyright (C) 2009-2022, Panagiotis Christopoulos Charitos and contributors.
// All rights reserved.
// Code licensed under the BSD License.
// http://www.anki3d.org/LICENSE

#pragma once

#include <AnKi/Shaders/Include/Common.h>

ANKI_BEGIN_NAMESPACE

/// Common data for all materials.
struct MaterialGlobalUniforms
{
	Mat4 m_viewProjectionMatrix;
	Mat3x4 m_viewMatrix;
	Mat3x4 m_cameraTransform;
};
ANKI_SHADER_STATIC_ASSERT(sizeof(MaterialGlobalUniforms) == 10 * sizeof(Vec4));

const U32 MATERIAL_SET_BINDLESS = 0u;
const U32 MATERIAL_SET_GLOBAL = 1u;
const U32 MATERIAL_SET_LOCAL = 2u;

//
// Global bindings
//
const U32 MATERIAL_BINDING_TRILINEAR_REPEAT_SAMPLER = 0u;
const U32 MATERIAL_BINDING_GLOBAL_UNIFORMS = 1u;
const U32 MATERIAL_BINDING_GPU_VIEWS = 2u;
const U32 MATERIAL_BINDING_LOCAL_UNIFORMS2 = 3u;

// Global vertex buffer in different formats
const U32 MATERIAL_BINDING_TEXTURE_BUFFER_R32_SFLOAT = 4u;
const U32 MATERIAL_BINDING_TEXTURE_BUFFER_R32G32_SFLOAT = 5u;
const U32 MATERIAL_BINDING_TEXTURE_BUFFER_R32G32B32_SFLOAT = 6u;
const U32 MATERIAL_BINDING_TEXTURE_BUFFER_R8G8B8A8_SNORM = 7u;
const U32 MATERIAL_BINDING_TEXTURE_BUFFER_R8G8B8A8_UINT = 8u;

// For forward shading
const U32 MATERIAL_BINDING_LINEAR_CLAMP_SAMPLER = 9u;
const U32 MATERIAL_BINDING_DEPTH_RT = 10u;
const U32 MATERIAL_BINDING_LIGHT_VOLUME = 11u;
const U32 MATERIAL_BINDING_CLUSTER_SHADING_UNIFORMS = 12u;
const U32 MATERIAL_BINDING_CLUSTER_SHADING_LIGHTS = 13u;
const U32 MATERIAL_BINDING_CLUSTERS = 14u;

//
// Local bindings
//
const U32 MATERIAL_BINDING_LOCAL_UNIFORMS = 0u;
const U32 MATERIAL_BINDING_RENDERABLE_GPU_VIEW = 1u;
const U32 MATERIAL_BINDING_BONE_TRANSFORMS = 2u;
const U32 MATERIAL_BINDING_PREVIOUS_BONE_TRANSFORMS = 3u;
const U32 MATERIAL_BINDING_FIRST_NON_STANDARD_LOCAL = 4u;

ANKI_END_NAMESPACE
