name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Debug_x64_VK:
    name: "Debug_x64_VK"
    runs-on: windows-2025

    steps:
    - name: Clone
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DANKI_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DANKI_EXTRA_CHECKS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug

  Debug_x64_D3D:
    name: "Debug_x64_D3D"
    runs-on: windows-2025

    steps:
    - name: Clone
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DANKI_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DANKI_EXTRA_CHECKS=ON -DANKI_GR_BACKEND=DIRECTX

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug

  Debug_arm64_VK:
    name: "Debug_arm64_VK"
    runs-on: windows-11-arm

    steps:
    - name: Clone
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DANKI_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DANKI_EXTRA_CHECKS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug

  Debug_arm64_D3D:
    name: "Debug_arm64_D3D"
    runs-on: windows-11-arm

    steps:
    - name: Clone
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DANKI_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DANKI_EXTRA_CHECKS=ON -DANKI_GR_BACKEND=DIRECTX

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug

  Release_x64_VK:
    name: "Release_x64_VK"
    runs-on: windows-2025

    steps:
    - name: Clone
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DANKI_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DANKI_EXTRA_CHECKS=OFF

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

  Release_x64_D3D:
    name: "Release_x64_D3D"
    runs-on: windows-2025

    steps:
    - name: Clone
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DANKI_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DANKI_EXTRA_CHECKS=OFF -DANKI_GR_BACKEND=DIRECTX

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

  DLSS_x64:
    name: "DLSS_x64"
    runs-on: windows-2025

    steps:
    - name: Clone
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DANKI_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Release -DANKI_EXTRA_CHECKS=OFF -DANKI_DLSS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release --target Sponza
